version: '3.5'
services:
    php:
      container_name: "reports_php"
      hostname: reports.engineroom.$USER.dev
      build:
        context: ./docker/php
#      image: digital360/php-nginx-alpine
      volumes:
        - ./app:/var/www/html
        - /etc/timezone:/etc/timezone:ro
      networks:
        - engineroom
      extra_hosts:
        - "api.engineroom.adriannorman.dev:172.19.0.5"
      environment:
        - APP_URL=https://reports.engineroom.$USER.dev
        - REDIS_PORT=6379
        - VIRTUAL_HOST=reports.engineroom.$USER.dev
        - SERVER_ROOT=/var/www/html/public
    redis:
      container_name: "reports_redis"
      image: "redis:alpine"
      ports:
        - "6300:6379"
      volumes:
        - redis_data:/var/lib/redis
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
volumes:
  redis_data:
networks:
  engineroom:
    external:
      name: docker_default
